name = "TransformerXAI"
uuid = "760f204d-c9d5-47fc-8112-97e58fae4ca6"
authors = ["Charansurya Udaysingh Jhurree <charansurya.udaysingh.jhurree@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Llama2 = "0e620e9f-4534-4490-8f63-949aea0a85e1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LinearAlgebra = "1.11.0"
Llama2 = "1.1.0"
StatsBase = "0.34.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
